recipes = [{ "_id" : "5c7ad2bffb6fc072012c83cc", "id" : "1", "recipe_name" : "Rich and Simple French Onion Soup", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/1081318.jpg", "cuisine_name" : "French", "course_name" : "soup", "ingredients" : [ "1/2 cup unsalted butter", "1/4 cup milk", "2 table spoons olive oil", "4 cups sliced onions", "4 (10.5 ounce) cans beef broth", "4 slices French bread", "4 slices provolone cheese", "salt and pepper to taste", "2 slices Swiss cheese, diced", "1/4 grated Parmesan cheese" ], "cooking_directions" : [ "Melt butter with olive oil in an 8 quart stock pot on medium heat. Add onions and continually stir until tender and translucent. Do not brown the onions.", "Add beef broth, sherry and thyme. Season with salt and pepper, and simmer for 30 minutes.", "Heat the oven broiler.", "Ladle soup into oven safe serving bowls and place one slice of bread on top of each (bread may be broken into pieces if you prefer). Layer each slice of bread with a slice of provolone, 1/2 slice diced Swiss and 1 tablespoon Parmesan cheese. Place bowls on cookie sheet and broil in the preheated oven until cheese bubbles and browns slightly." ], "allergen_name" : "milk", "author_name" : "Lori Levin", "preparation_time" : "15 min", "cooking_time" : "50 min", "views" : "1440", "servings" : "4", "calories" : "585 cals" },
{ "_id" : "5c7ad43efb6fc072012c862f", "id" : "2", "recipe_name" : "Lemon Madeleines", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/3890788.jpg", "cuisine_name" : "French", "course_name" : "dessert", "ingredients" : [ "2 eggs", "1/2 cup white sugar", "5 tablespoons unsalted butter", "3/4 cup all-purpose flour", "1 teaspoon baking powder", "1/4 teaspoon vanilla extract", "1/2 lemon, juiced and zested", "1/3 cup confectioners' sugar for decoration" ], "cooking_directions" : [ "In a large bowl blend eggs and sugar add butter and blend well. On low speed, blend in flour, baking powder, lemon, vanilla.", "Cover bowl with towel and let sit for one hour.", "Preheat oven to 375 degrees F (190 degrees C) and butter and flour madeleine molds. Whisk batter then spoon into molds 3/4 full. Bake 10 minutes. Remove from molds and cool. Dust with confectioners' sugar." ], "allergen_name" : "egg", "author_name" : "Kevin Ashley", "preparation_time" : "20 min", "cooking_time" : "40 min", "views" : "1676", "servings" : "12", "calories" : "129 cals" },
{ "_id" : "5c7b9468fb6fc072012cbeb8", "id" : "3", "recipe_name" : "Double Tomato Bruschetta", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/4542188.jpg", "cuisine_name" : "Italian", "course_name" : "appetizer", "ingredients" : [ "6 roma (plum) tomatoes", "chopped1/2 cup sun-dried tomatoes, packed in oil", "3 cloves minced garlic", "1/4 cup olive oil", "2 tablespoons balsamic vinegar", "1/4 cup fresh basil, stems removed", "1/4 teaspoon salt", "1/4 teaspoon ground black pepper", "1 French baguette", "2 cups shredded mozzarella cheese" ], "cooking_directions" : [ "Preheat the oven on broiler setting.", "In a large bowl, combine the roma tomatoes, sun-dried tomatoes, garlic, olive oil, vinegar, basil, salt, and pepper. Allow the mixture to sit for 10 minutes. ", "Cut the baguette into 3/4-inch slices. On a baking sheet, arrange the baguette slices in a single layer. Broil for 1 to 2 minutes, until slightly brown. ", "Divide the tomato mixture evenly over the baguette slices. Top the slices with mozzarella cheese. ", "Broil for 5 minutes, or until the cheese is melted." ], "allergen_name" : "garlic", "author_name" : "Laura Thompson", "preparation_time" : "15 min", "cooking_time" : "7 min", "views" : "1249", "servings" : "12", "calories" : "215 cals" },
{ "_id" : "5c7b9479fb6fc072012cbebf", "id" : "4", "recipe_name" : "Cholay (Curried Chickpeas)", "recipe_image" : "https://images.media-allrecipes.com/userphotos/250x250/18462.jpg", "cuisine_name" : "Indian", "course_name" : "main dish", "ingredients" : [ "2 cups water", "1 tea bag", "1 bay leaf", "2 (15.5 ounce) cans garbanzo beans, drained", "2 tablespoons vegetable oil, divided", "1 onion, sliced", "3 tomatoes, chopped", "1/4 cup fresh cilantro leaves", "1 teaspoon ground coriander", "1 teaspoon cumin seeds", "1 teaspoon grated fresh ginger root", "1 teaspoon grated garlic", "1 onion, finely chopped", "ground cayenne pepper to taste" ], "cooking_directions" : [ "Place the 2 cups water, tea bag, and bay leaf into a pot, and bring water to a boil. Reserving about 1/2 cup garbanzo beans, stir the beans into the boiling water. When beans are heated through, discard the tea bag and bay leaf. Remove from heat. Drain the beans, reserving water, and set aside.", "Heat 2 teaspoons oil in a skillet over medium heat, and saute the sliced onion until tender. Remove from heat, cool, and mix in the reserved garbanzo beans, 1 tomato, and 1/2 the cilantro leaves. Set aside.", "Heat the remaining oil in a skillet over medium heat. Blend in the coriander, cumin seeds, ginger, and garlic. Cook and stir for 15 to 20 seconds, until lightly browned. Mix in the turmeric. Stir the chopped onion into the skillet, and cook until tender. Mix in the remaining tomatoes. Season with salt, cayenne pepper, and garam masala. Bring the tomato liquid to a boil, and cook about 5 minutes. Stir in the boiled garbanzo beans, sliced onion mixture, and enough of the reserved water to attain a thick, gravy-like consistency. Continue to cook and stir 5 minutes. Garnish with the remaining cilantro leaves to serve." ], "allergen_name" : "garlic", "author_name" : "Shammi Edwards", "preparation_time" : "20 min", "cooking_time" : "25 min", "views" : "5647", "servings" : "6", "calories" : "248 cals" },
{ "_id" : "5c7b9497fb6fc072012cbed8", "id" : "5", "recipe_name" : "Italian Sausage Tortellini Soup", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/3962486.jpg", "cuisine_name" : "Italian", "course_name" : "soup", "ingredients" : [ "1 (3.5 ounce) link sweet Italian sausage, casings removed", "1 cup chopped onions", "2 cloves garlic, minced", "5 cups beef stock", "1/3 cup water", "1/2 cup red wine", "4 tomatoes - peeled, seeded and chopped", "1 cup chopped carrots", "1/2 teaspoon dried basil", "1/2 teaspoon dried oregano", "1 cup tomato sauce1 zucchini, chopped", "8 ounces cheese tortellini", "1 green bell pepper, chopped", "1 tablespoon chopped fresh parsley", "2 tablespoons grated Parmesan cheese for topping" ], "cooking_directions" : [ "Place the sausage in a large pot over medium high heat and saute for 10 minutes, or until well browned. Drain the fat except for about 1 tablespoon, add the onions and garlic and saute for 5 more minutes.", "Next add the beef stock, water, wine, tomatoes, carrots, basil, oregano and tomato sauce. Bring to a boil, reduce heat to low and simmer for 30 minutes, skimming any fat that may surface.", "Add the zucchini, tortellini, green bell pepper and parsley to taste. Simmer for 10 minutes, or until tortellini is fully cooked. Pour into individual bowls and garnish with the cheese." ], "allergen_name" : "garlic", "author_name" : "Tim Smith", "preparation_time" : "15 min", "cooking_time" : "55 min", "views" : "6789", "servings" : "6", "calories" : "249 cals" },
{ "_id" : "5c7b94a2fb6fc072012cbedd", "id" : "6", "recipe_name" : "Asian Lettuce Wraps", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/2630776.jpg", "cuisine_name" : "Asian", "course_name" : "dinner", "ingredients" : [ "16 Boston Bibb or butter lettuce leaves", "1 pound lean ground beef", "1 tablespoon cooking oil.", "1 large onion, chopped", "1/4 cup hoisin sauce", "2 cloves fresh garlic, minced", "1 tablespoon soy sauce", "1 tablespoon rice wine vinegar", "2 teaspoons minced pickled ginger", "1 (8 ounce) can water chestnuts, drained and finely chopped", "1 bunch green onions, chopped", "2 teaspoons Asian (dark) sesame oil" ], "cooking_directions" : [ "Rinse whole lettuce leaves and pat dry, being careful not tear them. Set aside.", "Heat a large skillet over medium-high heat. Cook and stir beef and cooking oil in the hot skillet until browned and crumbly, 5 to 7 minutes. Drain and discard grease; transfer beef to a bowl. Cook and stir onion in the same skillet used for beef until slightly tender, 5 to 10 minutes. Stir hoisin sauce, garlic, soy sauce, vinegar, ginger, and chile pepper sauce into onions. Add water chestnuts, green onions, sesame oil, and cooked beef; cook and stir until the onions just begin to wilt, about 2 minutes.", "Arrange lettuce leaves around the outer edge of a large serving platter and pile meat mixture in the center." ], "allergen_name" : "garlic and nuts", "author_name" : "Rachel Castro", "preparation_time" : "20 min", "cooking_time" : "15 min", "views" : "789", "servings" : "4", "calories" : "388 cals" },
{ "_id" : "5c7b94aefb6fc072012cbee1", "id" : "7", "recipe_name" : "Buche de Noel", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/3023127.jpg", "cuisine_name" : "French", "course_name" : "dessert", "ingredients" : [ "2 cups heavy cream", "1/2 cup confectioners' sugar", "1/2 cup unsweetened cocoa powder", "1 teaspoon vanilla extract", "6 egg yolks", "1/2 cup white sugar", "1/3 cup unsweetened cocoa powder", "1/8 teaspoon salt", "6 egg whites", "1/4 cup white sugar", "confectioners' sugar for dusting" ], "cooking_direction" : [ "Preheat oven to 375 degrees F (190 degrees C). Line a 10x15 inch jellyroll pan with parchment paper. In a large bowl, whip cream, 1/2 cup confectioners' sugar, 1/2 cup cocoa, and 1 teaspoon vanilla until thick and stiff. Refrigerate.", "In a large bowl, use an electric mixer to beat egg yolks with 1/2 cup sugar until thick and pale. Blend in 1/3 cup cocoa, 1 1/2 teaspoons vanilla, and salt. In large glass bowl, using clean beaters, whip egg whites to soft peaks. Gradually add 1/4 cup sugar, and beat until whites form stiff peaks. Immediately fold the yolk mixture into the whites. Spread the batter evenly into the prepared pan.", "Bake for 12 to 15 minutes in the preheated oven, or until the cake springs back when lightly touched. Dust a clean dishtowel with confectioners' sugar. Run a knife around the edge of the pan, and turn the warm cake out onto the towel. Remove and discard parchment paper. Starting at the short edge of the cake, roll the cake up with the towel. Cool for 30 minutes.", "Unroll the cake, and spread the filling to within 1 inch of the edge. Roll the cake up with the filling inside. Place seam side down onto a serving plate, and refrigerate until serving. Dust with confectioners' sugar before serving." ], "allergen_name" : "egg", "author_name" : "Tyrarachele", "preparation_time" : "45 min", "cooking_time" : "15", "views" : "1150", "servings" : "12", "calories" : "276 cals" },
{ "_id" : "5c7b94b7fb6fc072012cbee3", "id" : "8", "recipe_name" : "Main Dish Macaroni Salad", "recipe_image" : "https://images.media-allrecipes.com/userphotos/250x250/126834.jpg", "cuisine_name" : "Italian", "course_name" : "main dish", "ingredients" : [ "1 cup mayonnaise", "1/4 cup grated Parmesan cheese", "1/4 cup chopped parsley", "2 tablespoons milk", "1 clove garlic, minced", "2 cups corkscrew pasta", "1 1/2 cups diced ham", "2 cups halved cherry tomatoes" ], "cooking_directions" : [ "Cook pasta in a large pot of boiling water until al dente. Drain, rinse, and drain once more. Set aside.", "In a large bowl, combine mayonnaise, grated cheese, parsley, milk, and garlic. Mix well. Stir in pasta, ham, and tomatoes. Chill several hours." ], "allergen_name" : "milk and garlic", "author_name" : "Jill M.", "preparation_time" : "15 min", "cooking_time" : "10 min", "views" : "2894", "servings" : "7", "calories" : "342 cals" },
{ "_id" : "5c7b94c0fb6fc072012cbee4", "id" : "9", "recipe_name" : "Asian Mushroom Soup", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/4296.jpg", "cuisine_name" : "Asian", "course_name" : "soup", "ingredients" : [ "4 cups fat-free, reduced-sodium chicken broth", "3 tablespoons reduced-sodium soy sauce", "2 teaspoons grated fresh ginger", "3 garlic cloves, crushed", "3 cups assorted mushrooms, sliced", "3 cups white cabbage, cut in wedges", "1 cup thinly sliced carrots", "2 cups chicken breast, shredded", "2 cups fresh udon noodles", "1 cup thinly sliced green onions, with some of the green tops", "2 cups shredded raw spinach or whole baby spinach leaves", "freshly ground black pepper to taste" ], "cooking_directions" : [ "In a large pot, combine broth, soy sauce, ginger, garlic, mushrooms, cabbage, carrots and chicken. Cover. Bring to a boil; simmer until mushrooms are soft, about 5 minutes. Stir in noodles, green onions and spinach; simmer until greens are wilted, about 2 minutes. Season." ], "allergen_name" : "garlic", "author_name" : "Jean", "preparation_time" : "25 min", "cooking_time" : "45 min", "views" : "3004", "servings" : "6", "calories" : "192 cals" },
{ "_id" : "5c7b94cafb6fc072012cbeec", "id" : "10", "recipe_name" : "Greek Artichoke Appetizer", "recipe_image" : "https://images.media-allrecipes.com/userphotos/250x250/855793.jpg", "cuisine_name" : "Greek", "course_name" : "appetizer", "ingredients" : [ "2 (6 ounce) jars marinated artichoke hearts, divided", "1 small onion, finely chopped", "1 1/2 cloves garlic, minced", "4 large eggs, beaten", "1/4 cup dry bread crumbs", "1/4 teaspoon salt", "1/8 teaspoon ground black pepper", "1/4 teaspoon dried oregano", "1/2 teaspoon hot pepper sauce", "3/4 pound sharp Cheddar cheese, shredded", "2 tablespoons minced fresh parsley", "1 teaspoon grated Parmesan cheese" ], "cooking_directions" : [ "Preheat oven to 325 degrees F (165 degrees C).", "Grease a 10x7x2-inch baking dish.", "Drain marinade from one jar of artichoke hearts into a skillet.", "Pour artichoke hearts from drained jar and the entire second jar (marinade and artichoke hearts) into a food processor. Blend until artichoke hearts are coarsely chopped and set aside.", "Cook and stir onion and garlic in the skillet with marinade over medium-low heat until onions are light brown, 5 to 7 minutes. Remove from heat and transfer to a large bowl.", "Stir onion mixture, eggs, bread crumbs, salt, black pepper, oregano, and hot pepper sauce together until well mixed.", "Stir sharp Cheddar cheese, parsley, Parmesan cheese, and chopped artichoke heart mixture into the onion mixture. Pour mixture into prepared baking dish.", "Bake in preheated oven until top is golden, 25 to 30 minutes. Cut into 1-inch squares and serve warm or cold." ], "allergen_name" : "egg and garlic", "author_name" : "Bret Gentry", "preparation_time" : "30 min", "cooking_time" : "30 min", "views" : "5389", "servings" : "36", "calories" : "59 cals" },
{ "_id" : "5c7b94d4fb6fc072012cbeed", "id" : "11", "recipe_name" : "Irish Cocktail Cupcakes", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/6382465.jpg", "cuisine_name" : "Irish", "course_name" : "dessert", "ingredients" : [ "1 cup Irish stout beer", "9 tablespoons unsalted butter, cut into 1-inch pieces", "2 cups dark brown sugar", "3/4 cup unsweetened cocoa powder", "3/4 cup sour cream", "2 eggs", "1 tablespoon vanilla extract", "2 cups all-purpose flour", "2 1/2 teaspoons baking soda", "1 stick unsalted butter, at room temperature", "2 tablespoons Irish cream liqueur, or more to taste", "2 teaspoons Irish whiskey, or to taste", "3 cups confectioners' sugar" ], "cooking_directions" : [ "Preheat the oven to 350 degrees F (175 degrees C). Line a muffin tin with paper liners.", "Combine stout beer and butter in a large saucepan over low heat. Heat until butter melts, about 5 minutes. Remove from heat and whisk in brown sugar and cocoa.", "Whisk sour cream, eggs, and vanilla extract in a bowl; pour into the saucepan and mix until a smooth batter forms.", "Stir flour and baking soda together. Fold into the batter. Divide batter evenly among the prepared muffin cups.", "Bake in the preheated oven until a toothpick inserted into the center comes out clean, about 25 minutes. Leave in the tin for 10 minutes, then transfer to a wire rack to cool completely.", "Make frosting while the cupcakes cool. Place butter in a large mixing bowl and beat with an electric mixer on medium-high speed for 2 to 3 minutes. Mix in Irish cream and whiskey on low speed. Gradually spoon in confectioners' sugar, mixing on low speed until frosting is smooth and creamy.", "Spread frosting over cupcakes." ], "allergen_name" : "egg", "author_name" : "Inskydiamonds", "preparation_time" : "15 min", "cooking_time" : "30 min", "views" : "643", "servings" : "18", "calories" : "370 cals" },
{ "_id" : "5c7b94defb6fc072012cbeef", "id" : "12", "recipe_name" : "Curry Stand Chicken Tikka Masala Sauce", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/5504832.jpg", "cuisine_name" : "Indian", "course_name" : "main dish", "ingredients" : [ "2 tablespoons ghee (clarified butter)", "1 onion, finely chopped", "4 cloves garlic, minced", "1 tablespoon ground cumin", "1 teaspoon salt", "1 teaspoon ground ginger", "1 teaspoon cayenne pepper", "1/2 teaspoon ground cinnamon", "1/4 teaspoon ground turmeric", "1 (14 ounce) can tomato sauce", "1 cup heavy whipping cream", "2 teaspoons paprika", "1 tablespoon white sugar", "1 tablespoon vegetable oil", "4 skinless, boneless chicken breast halves, cut into bite-size pieces", "1/2 teaspoon curry powder" ], "cooking_directions" : [ "Heat ghee in a large skillet over medium heat and cook and stir onion until translucent, about 5 minutes. Stir in garlic; cook and stir just until fragrant, about 1 minute. Stir cumin, 1 teaspoon salt, ginger, cayenne pepper, cinnamon, and turmeric into the onion mixture; fry until fragrant, about 2 minutes.", "Stir tomato sauce into the onion and spice mixture, bring to a boil, and reduce heat to low. Simmer sauce for 10 minutes, then mix in cream, paprika, and 1 tablespoon sugar. Bring sauce back to a simmer and cook, stirring often, until sauce is thickened, 10 to 15 minutes.", "Heat vegetable oil in a separate skillet over medium heat. Stir chicken into the hot oil, sprinkle with curry powder, and sear chicken until lightly browned but still pink inside, about 3 minutes; stir often. Transfer chicken and any pan juices into the sauce. Simmer chicken in sauce until no longer pink, about 30 minutes; adjust salt and sugar to taste." ], "allergen_name" : "garlic", "author_name" : "Chris Bellers", "preparation_time" : "15 min", "cooking_time" : "1h 5 min", "views" : "14178", "servings" : "6", "calories" : "328 cals" },
{ "_id" : "5c7b94e8fb6fc072012cbef3", "id" : "13", "recipe_name" : "Quick Fish Tacos", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/1017268.jpg", "cuisine_name" : "Mexican", "course_name" : "dinner", "ingredients" : [ "1/4 cup reduced-fat sour cream", "2 tablespoons lime juicesalt and ground black pepper to taste", "1 jalapeno pepper, halved lengthwise", "2 1/2 cups shredded red cabbage", "4 green onions, thinly sliced", "2 tablespoons olive oil1 pound tilapia fillets, cut into strips", "8 (6 inch) flour tortillas", "1/2 cup chopped fresh cilantro" ], "cooking_directions" : [ "Mix sour cream and lime juice together in a large bowl; season with salt and black pepper. Reserve about half the mixture in another bowl for serving. Mince half the jalapeno pepper; save other half for later. Toss cabbage, green onions, and minced jalapeno half in remaining sour cream mixture until slaw is well mixed.", "Heat olive oil and remaining jalapeno half in a large skillet over medium heat; swirl oil to coat skillet evenly. Season tilapia fillets with salt and pepper. Pan-fry fish strips in the skillet in 2 batches until fish is golden brown and easily flaked with a fork, 5 to 6 minutes. Discard jalapeno half.", "Heat tortillas in the microwave on high until warm, 20 to 30 seconds.", "Serve fish in warmed tortillas topped with cabbage slaw, reserved sour cream mixture, and cilantro." ], "author_name" : "Huge", "preparation_time" : "20 min", "cooking_time" : "15 min", "views" : "3276", "servings" : "4", "calories" : "416 cals" },
{ "_id" : "5c7b94f2fb6fc072012cbef7", "id" : "14", "recipe_name" : "Indian Relish", "recipe_image" : "https://images.media-allrecipes.com/userphotos/250x250/86389.jpg", "cuisine_name" : "Indian", "course_name" : "dessert", "ingredients" : [ "2 red bell peppers, chopped", "1 sweet onion, peeled and chopped", "1 cup white wine vinegar", "1 cup white sugar", "1 tablespoon crushed red pepper flakes" ], "cooking_directions" : [ "In a medium saucepan over medium heat, mix together red bell peppers, onion, white wine vinegar, sugar and crushed red pepper flakes. Bring to a boil, then reduce heat to simmer. Stirring occasionally, cook 30 minutes, or until thickened. Refrigerate 4 hours or overnight before serving." ], "author_name" : "Cyndylee65", "preparation_time" : "5 min", "cooking_time" : "30 min", "views" : "473", "servings" : "24", "calories" : "38 cals" },
{ "_id" : "5c7b94fbfb6fc072012cbef8", "id" : "15", "recipe_name" : "Irish Cream Chocolate Cheesecake", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/32774.jpg", "cuisine_name" : "Irish", "course_name" : "dessert", "ingredients" : [ "1 1/2 cups chocolate cookie crumbs", "1/3 cup confectioners' sugar", "1/3 cup unsweetened cocoa powder", "1/4 cup butter", "3 (8 ounce) packages cream cheese, softened", "1 1/4 cups white sugar", "1/4 cup unsweetened cocoa powder", "3 tablespoons all-purpose flour", "3 eggs", "1/2 cup sour cream", "1/4 cup Irish cream liqueur" ], "cooking_directions" : [ "Preheat oven to 350 degrees F (175 degrees C). In a large bowl, mix together the cookie crumbs, confectioners' sugar and 1/3 cup cocoa. Add melted butter and stir until well mixed. Pat into the bottom of a 9 inch springform pan. Bake in preheated oven for 10 minutes; set aside. Increase oven temperature to 450 degrees F (230 degrees C).", "In a large bowl, combine cream cheese, white sugar, 1/4 cup cocoa and flour. Beat at medium speed until well blended and smooth. Add eggs one at a time, mixing well after each addition. Blend in the sour cream and Irish cream liqueur; mixing on low speed. Pour filling over baked crust.", "Bake at 450 degrees F (230 degrees C) for 10 minutes. Reduce oven temperature to 250 degrees F (120 degrees C), and continue baking for 60 minutes.", "With a knife, loosen cake from rim of pan. Let cool, then remove the rim of pan. Chill before serving. If your cake cracks, a helpful tip is to dampen a spatula and smooth the top, then sprinkle with some chocolate wafer crumbs." ], "allergen_name" : "egg", "author_name" : "Elaine", "preparation_time" : "20 min", "cooking_time" : "1h 20 min", "views" : "7865", "servings" : "12", "calories" : "457 cals" },
{ "_id" : "5c7b9505fb6fc072012cbef9", "id" : "16", "recipe_name" : "Asian Chicken Noodle Soup", "recipe_image" : "https://images.media-allrecipes.com/userphotos/250x250/334142.jpg", "cuisine_name" : "Asian", "course_name" : "soup", "ingredients" : [ "4 ounces dry Chinese noodles", "1 (14.5 ounce) can chicken broth", "6 shiitake mushrooms, sliced", "2 green onions, chopped", "1 skinless, boneless chicken breast half", "2 eggs" ], "cooking_directions" : [ "Bring a large pot of water to a boil. Stir noodles into boiling water and cook until al dente, 8 to 10 minutes. (For a chewier texture, shock the noodles by pouring 1 cup cold water into the pot when it starts to foam, then letting it come to a boil again to finish cooking.) Drain and divide into two serving bowls.", "Meanwhile, bring chicken broth to boil in a medium saucepan with mushrooms and green onions. Cut chicken into bite-sized pieces and stir into boiling broth. When broth returns to a boil, crack eggs into broth. Continue to cook until chicken is no longer pink and eggs are cooked, about 10 minutes. Pour the chicken soup over the noodles in the bowls and serve immediately." ], "allergen_name" : "egg", "author_name" : "Beverly", "preparation_time" : "10 min", "cooking_time" : "20 min", "views" : "4280", "servings" : "2", "calories" : "356 cals" },
{ "_id" : "5c7b9510fb6fc072012cbefa", "id" : "17", "recipe_name" : "Italian Rice Croquettes", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/1002149.jpg", "cuisine_name" : "Italian", "course_name" : "appetizer", "ingredients" : [ "2 pounds chicken giblets", "1 cup water", "1/2 teaspoon salt", "4 cups salted water", "2 cups long grain white rice, uncooked", "2 cups grated Parmesan cheese", "1/2 cup marinara sauce", "1/4 cup dry bread crumbs", "2 large eggs", "2 tablespoons chopped fresh parsley", "salt and freshly ground black pepper to taste", "1 cup dry bread crumbs for coating", "vegetable oil for frying" ], "cooking_directions" : [ "Combine chicken giblets, 1 cup water, and 1/2 teaspoon salt in a pressure cooker; cook for about 20 minutes.", "Drain giblets and let cool, about 10 minutes. Chop giblets in a food processor or by hand; set aside.", "Bring rice and water to a boil in a saucepan over high heat. Reduce heat to medium-low, cover, and simmer until the rice is tender, and the liquid has been absorbed, 20 to 25 minutes.", "Spread cooked rice onto a baking sheet to cool, about 5 minutes. Transfer rice to a large bowl.", "Mix in giblets, grated Parmesan cheese, marinara sauce, 1/4 cup bread crumbs, eggs, parsley, salt, and ground pepper. Cover with plastic wrap and refrigerate for 1 hour.", "Remove rice and giblet mixture from refrigerator and form 2-inch, football shaped croquettes. Roll croquettes in bread crumbs and place on a baking sheet.", "Heat oil in a large skillet over medium-high heat; cook breaded croquettes until browned on all sides, about 10 minutes. Transfer to a plate lined with paper towels to absorb excess oil." ], "allergen_name" : "egg", "author_name" : "Chef John", "preparation_time" : "50 min", "cooking_time" : "50 min", "views" : "2981", "servings" : "40", "calories" : "99 cals" },
{ "_id" : "5c7b951dfb6fc072012cbefd", "id" : "18", "recipe_name" : "Traditional Mexican Guacamole", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/848092.jpg", "cuisine_name" : "Mexican", "course_name" : "appetizer", "ingredients" : [ "2 avocados, peeled and pitted", "1 cup chopped tomatoes", "1/4 cup chopped onion", "1/4 cup chopped cilantro", "2 tablespoons lemon juice", "1 jalapeno pepper, seeded and minced", "salt and ground black pepper to taste" ], "cooking_directions" : [ "Mash avocados in a bowl until creamy.", "Mix tomatoes, onion, cilantro, lemon juice, and jalapeno pepper into mashed avocado until well combined; season with salt and black pepper." ], "author_name" : "Kaersten", "preparation_time" : "10 min", "cooking_time" : "10 min", "views" : "5532", "servings" : "4", "calories" : "176 cals" },
{ "_id" : "5c7b952bfb6fc072012cbeff", "id" : "19", "recipe_name" : "Chicken Cordon Bleu", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/4535588.jpg", "cuisine_name" : "French", "course_name" : "dinner", "ingredients" : [ "6 skinless, boneless chicken breast halves", "6 slices Swiss cheese", "6 slices ham", "3 tablespoons all-purpose flour", "1 teaspoon paprika", "6 tablespoons butter", "1/2 cup dry white wine", "1 teaspoon chicken bouillon granules", "1 tablespoon cornstarch", "1 cup heavy whipping cream" ], "cooking_directions" : [ "Pound chicken breasts if they are too thick. Place a cheese and ham slice on each breast within 1/2 inch of the edges. Fold the edges of the chicken over the filling, and secure with toothpicks. Mix the flour and paprika in a small bowl, and coat the chicken pieces.", "Heat the butter in a large skillet over medium-high heat, and cook the chicken until browned on all sides. Add the wine and bouillon. Reduce heat to low, cover, and simmer for 30 minutes, until chicken is no longer pink and juices run clear.", "Remove the toothpicks, and transfer the breasts to a warm platter. Blend the cornstarch with the cream in a small bowl, and whisk slowly into the skillet. Cook, stirring until thickened, and pour over the chicken. Serve warm." ], "author_name" : "Behr", "preparation_time" : "15 min", "cooking_time" : "45 min", "views" : "5426", "servings" : "6", "calories" : "584 cals" },
{ "_id" : "5c7b9535fb6fc072012cbf00", "id" : "20", "recipe_name" : "World's Best Lasagna", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/3359675.jpg", "cuisine_name" : "Italian", "course_name" : "main dish", "ingredients" : [ "1 pound sweet Italian sausage", "3/4 pound lean ground beef", "1/2 cup minced onion", "2 cloves garlic, crushed", "1 (28 ounce) can crushed tomatoes", "2 (6 ounce) cans tomato paste", "2 (6.5 ounce) cans canned tomato sauce", "1/2 cup water", "2 tablespoons white sugar", "1 1/2 teaspoons dried basil leaves", "1/2 teaspoon fennel seeds", "1 teaspoon Italian seasoning", "1 tablespoon salt", "1/4 teaspoon ground black pepper", "4 tablespoons chopped fresh parsley", "12 lasagna noodles", "16 ounces ricotta cheese", "1 egg", "1/2 teaspoon salt", "3/4 pound mozzarella cheese, sliced", "3/4 cup grated Parmesan cheese" ], "cooking_directions" : [ "In a large bowl blend eggs and sugar add butter and blend well. On low speed, blend in flour, baking powder, lemon, vanilla.", "Cover bowl with towel and let sit for one hour.", "Preheat oven to 375 degrees F (190 degrees C) and butter and flour madeleine molds. Whisk batter then spoon into molds 3/4 full. Bake 10 minutes. Remove from molds and cool. Dust with confectioners' sugar." ], "allergen_name" : "egg and garlic", "author_name" : "John Chandler", "preparation_time" : "30 min", "cooking_time" : "2h 30 min", "views" : "7045", "servings" : "12", "calories" : "448 cals" },
{ "_id" : "5c7b9483fb6fc072012cbec9", "id" : "23", "recipe_name" : "California Roll Sushi", "recipe_image" : "https://images.media-allrecipes.com/userphotos/250x250/907484.jpg", "cuisine_name" : "Asian", "course_name" : "appetizer", "ingredients" : [ "1 cup uncooked short-grain white rice", "1 cup water", "1/4 cup rice vinegar", "1 tablespoon white sugar", "1/2 cup imitation crabmeat, finely chopped", "1/4 cup mayonnaise", "8 sheets nori (dry seaweed)", "2 1/2 tablespoons sesame seeds", "1 cucumber, cut into thin spears", "2 avocados - pitted, peeled, and sliced the long way" ], "cooking_directions" : [ "Wash the rice in several changes of water until the rinse water is no longer cloudy, drain well, and place in a covered pan or rice cooker with 1 cup water. Bring to a boil, reduce heat to a simmer, and cover the pan. Allow the rice to simmer until the top looks dry, about 15 minutes. Turn off the heat, and let stand for 10 minutes to absorb the rest of the water.", "Mix the rice vinegar and sugar in a small bowl until the sugar has dissolved, and stir the mixture into the cooked rice until well combined. Allow the rice to cool, and set aside.", "Mix the imitation crabmeat with mayonnaise in a bowl, and set aside. To roll the sushi, cover a bamboo rolling mat with plastic wrap. Lay a sheet of nori, shiny side down, on the plastic wrap. With wet fingers, firmly pat a thin, even layer of prepared rice over the nori, leaving 1/4 inch uncovered at the bottom edge of the sheet. Sprinkle the rice with about 1/2 teaspoon of sesame seeds, and gently press them into the rice. Carefully flip the nori sheet over so the seaweed side is up.", "Place 2 or 3 long cucumber spears, 2 or 3 slices of avocado, and about 1 tablespoon of imitation crab mixture in a line across the nori sheet, about 1/4 from the uncovered edge. Pick up the edge of the bamboo rolling sheet, fold the bottom edge of the sheet up, enclosing the filling, and tightly roll the sushi into a cylinder about 1 1/2 inch in diameter. Once the sushi is rolled, wrap it in the mat and gently squeeze to compact it tightly.", "Cut each roll into 1 inch pieces with a very sharp knife dipped in water." ], "author_name" : "Erin", "preparation_time" : "45 min", "cooking_time" : "15 min", "likes" : "0", "servings" : "8", "calories" : "232 cals" },
{ "_id" : "5c7b948dfb6fc072012cbecc", "id" : "24", "recipe_name" : "Greek Lemon Chicken and Potatoes", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/4539284.jpg", "cuisine_name" : "Greek", "course_name" : "dinner", "ingredients" : [ "4 pounds skin-on, bone-in chicken thighs", "1 tablespoon kosher salt", "1 tablespoon dried oregano", "1 teaspoon freshly ground black pepper", "1 teaspoon dried rosemary", "1 pinch cayenne pepper", "1/2 cup fresh lemon juice", "1/2 cup olive oil", "6 cloves garlic, minced", "3 russet potatoes, peeled and quartered", "2/3 cup chicken broth, plus splash to deglaze panchopped fresh oregano for garnish" ], "cooking_directions" : [ "Preheat oven to 425 degrees F (220 degrees C). Lightly oil a large roasting pan.", "Place chicken pieces in large bowl. Season with salt, oregano, pepper, rosemary, and cayenne pepper. Add fresh lemon juice, olive oil, and garlic. Place potatoes in bowl with the chicken; stir together until chicken and potatoes are evenly coated with marinade.", "Transfer chicken pieces, skin side up, to prepared roasting pan, reserving marinade. Distribute potato pieces among chicken thighs. Drizzle with 2/3 cup chicken broth. Spoon remainder of marinade over chicken and potatoes.", "Place in preheated oven. Bake in the preheated oven for 20 minutes. Toss chicken and potatoes, keeping chicken skin side up; continue baking until chicken is browned and cooked through, about 25 minutes more. An instant-read thermometer inserted near the bone should read 165 degrees F (74 degrees C). Transfer chicken to serving platter and keep warm.", "Set oven to broil or highest heat setting. Toss potatoes once again in pan juices. Place pan under broiler and broil until potatoes are caramelized, about 3 minutes. Transfer potatoes to serving platter with chicken.", "Place roasting pan on stove over medium heat. Add a splash of broth and stir up browned bits from the bottom of the pan. Strain; spoon juices over chicken and potatoes. Top with chopped oregano." ], "allergen_name" : "garlic", "author_name" : "Chef John", "preparation_time" : "10 min", "cooking_time" : "50 min", "views" : "696", "servings" : "4", "calories" : "1139 cals" },
{ "_id" : "5c7b9540fb6fc072012cbf01", "id" : "21", "recipe_name" : "Easy English Muffins", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/3345383.jpg", "cuisine_name" : "English", "course_name" : "dessert", "ingredients" : [ "1 1/2 teaspoons active dry yeast, divided", "2 cups all-purpose flour, divided, plus more for rolling", "3/4 cup warm water, divided", "2 teaspoons vegetable oil", "1 teaspoon kosher salt", "1 egg white", "2 tablespoons cornmeal, or as needed", "1/4 cup clarified butter (ghee)" ], "cooking_directions" : [ "Place 1/4 cup flour, yeast, and 1/2 cup water in a mixing bowl. Whisk together and set aside for about 10 minutes to see if thin layer of foam develops to ensure yeast is active. Drizzle in vegetable oil; add salt, egg white, remaining 1 3/4 cup flour, and remaining 1/4 cup warm water. Mix together until dough is very wet and sticky. Cover. Set in a warm spot and let rise until doubled, about 2 hours.", "Pull dough gently from sides of bowl, stirring slightly, and turn out onto a well-floured rolling surface. Work in just enough flour until dough is easily handled and can be cut into 6 pieces, about 1 minute. Cut dough into 6 equal portions. Form a seamless ball of dough, adding a pinch of flour to keep it from sticking. Flatten to make thick disks. Transfer dough onto a lined baking sheet sprinkled generously with cornmeal. Let rise until doubled, about 1 to 1 1/2 hours.", "Add clarified butter to skillet over medium heat. Carefully transfer muffin disks to skillet. Cook in batches to avoid overcrowding. Brown on one side, 5 or 6 minutes. Turn, and brown the other side, 5 or 6 minutes. Continue turning to get muffins evenly browned and cooked through, 7 or 8 minutes total per side. Transfer to a cooking rack and cool completely (this is key as you can't split the muffins unless they are cooled).", "Split cooled muffins with a fork, inserting tines all the way around edges so the 2 sides can be pulled apart. Toast and serve with jam." ], "allergen_name" : "egg", "author_name" : "Chef John", "preparation_time" : "10 min", "cooking_time" : "14 min", "views" : "6553", "servings" : "6", "calories" : "256 cals" },
{ "_id" : "5c7b954afb6fc072012cbf04", "id" : "22", "recipe_name" : "Cider-Braised Pork Shoulder", "recipe_image" : "https://images.media-allrecipes.com/userphotos/560x315/4565575.jpg", "cuisine_name" : "English", "course_name" : "main dish", "ingredients" : [ "1 (3 pound) pork shoulder roast, cut into 3- or 4-inch chunks", "Kosher salt to generously season pork", "1 tablespoon vegetable oil", "1 large onion, chopped", "1 teaspoon salt, plus more to taste", "1/2 teaspoon freshly ground black pepper", "1/4 cup fresh sage leaves, torn", "1 (750 milliliter) bottle hard apple cider", "1/3 cup apple cider vinegar", "1/2 cup creme fraiche or heavy cream", "1 pinch cayenne pepper", "Creme fraiche for garnish", "Chopped fresh chives for garnish" ], "cooking_directions" : [ "Generously salt all sides of the pork shoulder chunks. Heat oil in a heavy pot over high heat. Brown pork shoulder pieces until surface is seared and crusty, about 3 or 4 minutes per side. Transfer browned pork to a plate. Add onions to oil and reduce heat to medium and season with a pinch of salt and pepper. Cook and stir about 2 minutes. Add torn sage leaves; cook until onions soften and begin to brown, stirring frequently. Pour cider into pot; stir to deglaze bottom. Raise heat to high and bring to a boil. Stir in cider vinegar. Reduce heat to low.", "Transfer pork shoulder pieces to cider mixture. Cover; simmer gently on low 1 hour. Remove lid and turn pieces over. Cover; simmer on low until meat is fork tender, 1 to 2 more hours. Transfer pork to a bowl with a slotted spoon.", "Raise heat to high and bring sauce to a simmer. Whisk in creme fraiche. Simmer until liquid is reduced by half and is slightly thickened, 8 to 10 minutes. Stir in a pinch of cayenne. Transfer pork back to pot; reduce heat to low. Baste pork with sauce while it heats through and becomes perfectly tender, and the sauce is as thick as you want it, about 15 more minutes." ], "author_name" : "Chef John", "preparation_time" : "10 min", "cooking_time" : "2h 15 min", "views" : "8490", "servings" : "4", "calories" : "696 cals" }]


""" Find ingredients by cuisine """

# def count_ingredients():
#     count_sugar = 0
#     count_milk = 0
#     count_egg = 0
#     count_flour = 0
#     count_salt = 0
#     count_water = 0
#     count_garlic = 0
#     count_vanilla = 0
#     count_butter = 0
#     for recipe in recipes:
#         if recipe["cuisine_name"] == "Irish":  # Change the name of the cuisine to look for other cuisines
#             items = []
#             for ingredient in recipe["ingredients"]:
#                 itemSplit = ingredient.split(",")
#                 itemSplitAtSpace = itemSplit[0].split(" ")
#                 items.append(itemSplitAtSpace)
#             # print(items)
#                 mergedItems = []
#                 removedDuplicates = []
#                 for item in items:
#                     mergedItems += item
#                     for mergedItem in mergedItems:
#                         if mergedItem not in removedDuplicates:
#                             removedDuplicates.append(mergedItem)
#             # print(mergedItems)
#             print(removedDuplicates)
#             """Change the name of the ingredient to search for another ingredient"""
#             if "milk" in removedDuplicates: 
#                 count_milk += 1
#             else:
#                 count_milk += 0
#             print(count_milk)
#             if ("egg" in removedDuplicates) | ("eggs" in removedDuplicates):
#                 count_egg += 1
#             else:
#                 count_egg += 0
#             print(count_egg)
#             if "sugar" in removedDuplicates:
#                 count_sugar += 1
#             else:
#                 count_sugar += 0
#             print(count_sugar)
#             if "flour" in removedDuplicates:
#                 count_flour += 1
#             else:
#                 count_flour += 0
#             print(count_flour)
#             if "salt" in removedDuplicates:
#                 count_salt += 1
#             else:
#                 count_salt += 0
#             print(count_salt)
#             if "water" in removedDuplicates:
#                 count_water += 1
#             else:
#                 count_water += 0
#             print(count_water)
#             if "garlic" in removedDuplicates:
#                 count_garlic += 1
#             else:
#                 count_garlic += 0
#             print(count_garlic)
#             if "vanilla" in removedDuplicates:
#                 count_vanilla += 1
#             else:
#                 count_vanilla += 0
#             print(count_vanilla)
#             if "butter" in removedDuplicates:
#                 count_butter += 1
#             else:
#                 count_butter += 0
#             print(count_butter)
# count_ingredients()

""" Percentage of allergens (from all recipes) """
    
# allergens = []
# def percent_allergens():
#     count_recipes = 0
#     count_none = 0
#     count_egg_allergen = 0
#     count_garlic_allergen = 0
#     count_nuts_allergen = 0
#     count_milk_allergen = 0
#     for recipe in recipes:
#         count_recipes += 1
#         # print(count_recipes)
#         if recipe.get('allergen_name') == None:
#             count_none += 1
#             # print(count_none)
#         else:
#             allergens.append(recipe["allergen_name"])
#     # print(allergens)
#     mergedAllergens = []
#     for allergen in allergens:
#         allergenSplit = allergen.split(" ")
#         # print(allergenSplit)
#         mergedAllergens.append(allergenSplit)
#     # print(mergedAllergens)
#     splitAllergens = []
#     for item in mergedAllergens:
#         splitAllergens += item
#     print(splitAllergens)
#     for word in splitAllergens:
#         if word == "egg":
#             count_egg_allergen += 1
#             # print(count_egg_allergen)
#         elif word == "garlic":
#             count_garlic_allergen += 1
#             print(count_garlic_allergen)
#         elif word == "nuts":
#             count_nuts_allergen += 1
#             # print(count_nuts_allergen)
#         elif word == "milk":
#             count_milk_allergen += 1
#             # print(count_milk_allergen)
#     percent_egg = (count_egg_allergen / count_recipes) * 100
#     print(percent_egg)
#     percent_milk = (count_milk_allergen / count_recipes) * 100
#     print(percent_milk)
#     percent_nuts = (count_nuts_allergen / count_recipes) * 100
#     print(percent_nuts)
#     percent_garlic = (count_garlic_allergen / count_recipes) * 100
#     print(percent_garlic)
#     percent_no_allergens = (count_none / count_recipes) * 100
#     print(percent_no_allergens)
            
# percent_allergens()


""" Average calories by cuisine """


def average_calories():
    calories_total = 0
    count_recipes_by_cuisine = 0
    for recipe in recipes:
        """ Change the name of cuisine to search for calories by another cuisine
            (Note: comment this out to calculate average calories for all recipes) """
        if recipe["cuisine_name"] == "Irish":
            count_recipes_by_cuisine += 1
            wordSplit = recipe["calories"].split(" ")
            # print(wordSplit)
            calories = int(wordSplit[0])
            calories_total += calories
            # print(calories_total)
            average_calories = calories_total / count_recipes_by_cuisine
    print(average_calories)
            
average_calories()



    




    

    
    
